name: run my Cypress tests (functional)
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    name: Test on Node v${{ matrix.node }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v3
        timeout-minutes: 10
        with:
          browser: firefox